# Generated by Django 5.2 on 2025-05-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="integrity_check",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client", name="car_license", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="client", name="engine_number", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="client", name="name", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="client", name="phone", field=models.TextField(),
        ),
    ]
